name: ATOOMO Docker Build and Push

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Build Docker image
      run: docker build -t atoomo -f ./docker/Dockerfile .

    - name: Generate tag and push to Docker Hub
      run: |
        TAG=$(echo "${GITHUB_REF##*/}-$(date +'%Y%m%d%H%M%S')")
        docker tag atoomo "${DOCKER_REPO}:${TAG}"
        docker push "${DOCKER_REPO}:${TAG}"
