name: ATOOMO Docker Build Tag Push

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t atoomo -f ./docker/Dockerfile .

    - name: Generate tag and push to Docker Hub
      run: |
        TAG=$(echo "${GITHUB_REF##*/}-$(date +'%Y%m%d%H%M%S')")
        docker tag atoomo "atoomo:${TAG}"
        docker push "atoomo:${TAG}"

